image: Visual Studio 2017
build_script:
- ps: >-
    [xml]$doc = (Get-Content .\RawDiskLib\RawDiskLib.csproj)

    [string]$version = $doc.Project.PropertyGroup.VersionPrefix
    
    Update-AppveyorBuild -Version "$($version.Trim()).$env:APPVEYOR_BUILD_NUMBER"
- ps: # Library
- ps: msbuild /t:Build /p:Configuration=Release RawDiskLib
- ps: # Pack Library
- ps: msbuild /t:Pack /p:Configuration=Release /p:OutputPath=..\Nuget\ RawDiskLib
- ps: # Library
- ps: msbuild /t:Build /p:Configuration=Release Examples\TestApplication
install:
- msbuild /t:Restore
artifacts:
- path: Nuget\*.nupkg
deploy:
- provider: NuGet
  api_key:
    secure: XQybZYLnmztB8KAUBRIo8CZsMzCqS+crt3bCEWDfRmFj9IMYFTyW1OwktjA5RMGA
  on:
    branch: nuget