build_script:
- ps: >-
    $version = (Get-Content .\RawDiskLib\project.json | ConvertFrom-Json).version

    Update-AppveyorBuild -Version "$version.$env:APPVEYOR_BUILD_NUMBER"
- ps: >-
    # Core

    dotnet restore
- ps: >-
    # Library

    dotnet pack -c Release -o Nuget\ RawDiskLib
- ps: >-
    # Utilities

    dotnet build -c Release Examples\TestApplication
artifacts:
- path: Nuget\*.nupkg
deploy:
- provider: NuGet
  api_key:
    secure: dgfUEGXULcqCTyNcS6UEDK8BCBi8y+M2+d4IFjnb3Gf9DqV34fMSp1XjxJg2AVRC
  on:
    branch: nuget